### PR TITLE
[Common] Reduce Dependency complexity to increase the SAM score @open sesame 07/13 11:38 

### PR DESCRIPTION
**Pull request by again4you**
There are lots of modules in /get/nnstreamer folder and it causes a high
dependency complexity. This PR reduces the module number by
integrating `elements`. Eventually it increases the DEP score from 2.73
to 5.0.

Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>

#### V4
* Add main `README.md` file for NNStreamer Elements and link to other markdown files.

#### V3
* Modify the file name of the element such as `gsttensor-[Function]` style instead `gsttensor[Function]`.
* Apply the common naming rule to non-core files as below.
  * `converter-media-info-audio.h` -> `gsttensor_converter_media_info_audio.h`
  * `converter-media-info-no-audio.h` -> `gsttensor_converter_media_no_audio.h`
  * `converter-media-info-no-video.h` -> `gsttensor_converter_media_no_video.h`
  * `converter-media-info-video.h` -> `gsttensor_converter_media_info_video.h`
  * `transform-orc.orc` -> `nnstreamer-orc.orc`
  * `tensordec.[c|h]` ->`gsttensor_decoder.[c|h]`

#### V2
* Integrate into `elements` folder except tensor-filter and tensor-query.
* Modify the file name of the element such as `gsttensor[Function]` style.
* Update the markdown file name and `sitemap.txt` for hotdoc.
* Update the Android NDK build file.

#### V1
* First draft
* Improve the DEP score from 2.73 to 5.0.

### CODE REVIEW

**Review by myungjoo — COMMENTED** [review]
1. Apply the common naming rule to non-core files, too (e.g., converter-media-info-no-video.h), so that others can easily group files for their elements.
2. gsttensorelementname.* --> gsttensor_elementname.* for better readability.

**Comment by jaeyun-jung** [comment]
file name to be updated
- tensordec to tensordecoder

**Comment by again4you** [comment]
#### V3
* Modify the file name of the element such as `gsttensor-[Function]` style instead `gsttensor[Function]`.
* Apply the common naming rule to non-core files as below.
  * `converter-media-info-audio.h` -> `gsttensor_converter_media_info_audio.h`
  * `converter-media-info-no-audio.h` -> `gsttensor_converter_media_no_audio.h`
  * `converter-media-info-no-video.h` -> `gsttensor_converter_media_no_video.h`
  * `converter-media-info-video.h` -> `gsttensor_converter_media_info_video.h`
  * `transform-orc.orc` -> `nnstreamer-orc.orc`
  * `tensordec.[c|h]` ->`gsttensor_decoder.[c|h]`

**Review by wooksong — COMMENTED** [review]
Since I am not sure what is the context under this PR, I have a question. Is it required to change the test cases (and the name of the directories containing them) according to the plug-ins' file name changes as well?

**Review by myungjoo — COMMENTED** [review]
The *.md files are not in order. There should be a main README.md that links to other *.md file.

**Comment by wooksong** [comment]
> > Since I am not sure what is the context under this PR, I have a question. Is it required to change the test cases (and the name of the directories containing them) according to the plug-ins' file name changes as well?\
> 
> The main purpose of this PR is to increase the DEP Score. Since the `register` module is referred to by all other elements, so Max Fan-out of this module is 17. Because of this reason, we decided to merge a single module except `Tensor-Filter` and `Tensor-Query`.
> 
> In my opinion, the test case is different from normal elements so we don't need to do that. Separate test cases are more easy to understand.

Thanks. I got it.

**Comment by again4you** [comment]
#### V4
* Add main `README.md` file for NNStreamer Elements and link to other markdown files.

**Review by myungjoo — APPROVED** [review]
LGTM

**Review by jaeyun-jung — APPROVED** [review]

**Pull request merged**
