### PR TITLE
[If] fix typo @open sesame 3/4 09:13

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Fix typo, property name of tensor-if element.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by zhoonit — APPROVED** [review]
LGTM!

**Review by myungjoo — APPROVED** [review]
LGTM

**Review by again4you — APPROVED** [review]
Nice catch!

**Review by gichan-jang — APPROVED** [review]
LGTM

**Pull request merged**
