### PR TITLE
[Build] framework priority option

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Add meson-option to set fw priority for file extension (.nb, .bin)

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by again4you — APPROVED** [review]
Nice work.
```bash
[Normal case]
framework_priority_nb=
framework_priority_bin=openvino

[VD case]
framework_priority_nb=vd_aifw
framework_priority_bin=vd_aifw
```

**Comment by gichan-jang** [comment]
The number of models is also used when auto-detecting the framework.
In this case, there is no overlap yet, so do we need priorities?

**Comment by jaeyun-jung** [comment]
@gichan-jang For only one mode file (.ext), now we didn't consider multi-models case to detect fw from conf file.

**Review by gichan-jang — APPROVED** [review]
LGTM

**Pull request merged**
