### PR TITLE
[Filter] Fix memory leak

### PR DESCRIPTION
**Pull request by gichan-jang**
Fix mem leak of the tensor filter.
Related issue: #3055 

Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>

Self evaluation:
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
We should keep current nn-framework version in filter-private struct.
Calling gst_tensor_filter_common_free_property() after closing nnfw causes res leak.

We cannot check fw version because fw is null, then prop->accl_str (for V0) prop->hw_list (for V1) is leak.
```
  if (GST_TF_FW_V0 (priv->fw)) {
    g_free_const (prop->accl_str);
  } else if (GST_TF_FW_V1 (priv->fw)) {
    g_free (prop->hw_list);
  }
```

**Comment by gichan-jang** [comment]
> We should keep current nn-framework version in filter-private struct.
> Calling gst_tensor_filter_common_free_property() after closing nnfw causes res leak.
> 
> We cannot check fw version because fw is null, then prop->accl_str (for V0) prop->hw_list (for V1) is leak.
> 
> ```
>   if (GST_TF_FW_V0 (priv->fw)) {
>     g_free_const (prop->accl_str);
>   } else if (GST_TF_FW_V1 (priv->fw)) {
>     g_free (prop->hw_list);
>   }
> ```

Thanks! Updated.

**Review by jaeyun-jung — APPROVED** [review]
LGTM. Please add another PR to lts-1.6 branch after merging this to main branch.

**Comment by dongju-chae** [comment]
FYI, Ubuntu build will be working after `pbuilder update` (compatible grpc version: `1.30.5-0~202102090627`).

**Review by myungjoo — COMMENTED** [review]
I suggest:

1. add a flag in GstTensorFilterProperties for the union, which tells you which to free.
or
2. Un-union the two and free both. (set NULL when unused)

Then you don't need to add an element for the deallocated element, which is very weird and you can remove the if statement of Line 1006.

**Comment by gichan-jang** [comment]
> I suggest:
> 
> 1. add a flag in GstTensorFilterProperties for the union, which tells you which to free.
>    or
> 2. Un-union the two and free both. (set NULL when unused)
> 
> Then you don't need to add an element for the deallocated element, which is very weird and you can remove the if statement of Line 1006.

Accl_str and hW_list are separated. Thanks.

**Review by myungjoo — APPROVED** [review]
LGTM

**Pull request merged**
