### PR TITLE
Test LLVM/Clang build in github-action

### LINKED ISSUE #3979: [CI/Clang] How about adding a new GitHub Actions workflow that checks clang-build?
**Is your feature request related to a problem? Please describe.**
Related to #3978 

**Describe the solution you'd like**
As the other checks with GCC do, it would be helpful if CI checks the clang-build.

**Describe alternatives you've considered**
At the current moment, rejecting PRs by the proposed workflow looks a little bit improper.
Instead, just checking might be OK.

### PR DESCRIPTION
**Pull request by myungjoo**
This fixes #3979 (CC @wooksong )

1st commit:

commit 3fe9ae56a19aff98a77d24862a2a3dbc756dfa7d
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Fri Oct 13 18:16:58 2023 +0900

    Support clang/clang++
    
    Fix clang's complaints.
    Addressing #3979
    
    To build w/ LLVM, do
    $ CC=clang CXX=clang++ meson ...
    
    Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

2nd commit:

commit 9d27be517d23d14ab097af0c954ac0d7f28ad024
Date:   Fri Oct 13 18:55:48 2023 +0900

    github-action: ubuntu-llvm/clang build test
    
    Add llvm/clang build test.
    Fixes #3979
    
    Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

**Comment by myungjoo** [comment]
My clang version was too low. I'll add further update for recent clang versions.

**Comment by myungjoo** [comment]
The CI error w/ GBS TIzen build is to be fixed by https://github.com/nnstreamer/nntrainer/pull/2334 
You may proceed without passing that one.

**Review by niley7464 — APPROVED** [review]
LGTM!

**Review by anyj0527 — APPROVED** [review]
LGTM👍 Cool!

**Pull request merged**
