### PR TITLE
Decoder/BoundingBox: fix resolution decoding @open sesame 10/13 18:20

### LINKED ISSUE #2781: Using output resolution instead of input resolution in boundingbox TF mode
Hi guys.
In ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
On _get_objects_tf macro (lines 779-782)
box coordinates should be multiplied in input dimensions instead of output dimensions.
instead of:
      object.x = (int) (boxes_[d * boxbpi + 1] * **bb->width**); \
      object.y = (int) (boxes_[d * boxbpi] * **bb->height**); \
      object.width = (int) ((boxes_[d * boxbpi + 3] - boxes_[d * boxbpi + 1]) * **bb->width**); \
      object.height = (int) ((boxes_[d * boxbpi + 2] - boxes_[d * boxbpi]) * **bb->height**); \

should be:
      object.x = (int) (boxes_[d * boxbpi + 1] * **bb->i_width**); \
      object.y = (int) (boxes_[d * boxbpi] * **bb->i_height**); \
      object.width = (int) ((boxes_[d * boxbpi + 3] - boxes_[d * boxbpi + 1]) * **bb->i_width**); \
      object.height = (int) ((boxes_[d * boxbpi + 2] - boxes_[d * boxbpi]) * **bb->i_height**); \

### PR DESCRIPTION
**Pull request by myungjoo**
draw() assumes that the "results" have coordinates based on
input resolutions, not output resolutions

Fixes #2781

Reported-by: @giladnahor
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

ps. We need to test with actual GUI demo app with largely different input-output resolutions.

### CODE REVIEW

**Comment by myungjoo** [comment]
Something doesn't add up...

**Comment by myungjoo** [comment]
Found that test cases are to be fixed. I'll add test-case-fix to this PR.

**Review by dongju-chae — APPROVED** [review]
LGTM

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by helloahn — APPROVED** [review]
LGTM

**Pull request merged**
