### PR TITLE
[doc] query and image update

### PR DESCRIPTION
**Pull request by niley7464**
This patch updates query and image for tutorial 4

Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped

### CODE REVIEW

**Comment by gichan-jang** [comment]
There is a black space in the first line of the query server element in `Documentation/tutorials/T4_object_detection_query.png`. Please check and remove it.

**Review by myungjoo — APPROVED** [review]
LGTM

**Comment by niley7464** [comment]
> There is a black space in the first line of the query server element in `Documentation/tutorials/T4_object_detection_query.png`. Please check and remove it.

I fixed it! Thank you

**Review by gichan-jang — APPROVED** [review]
LGTM

**Pull request merged**
