### PR TITLE
[Python] path to python helper lib

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Change install path for python-helper library.
This is to fix library link error.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by gichan-jang — APPROVED** [review]
LGTM.
This patch resolves the library link error mentioned in #3757.

**Review by myungjoo — COMMENTED** [review]
and... do you think we need to rename it?

e.g., "libnnstreamer-python3.so"

**Comment by jaeyun-jung** [comment]
> and... do you think we need to rename it?
> 
> e.g., "libnnstreamer-python3.so"

I think this is related with python module name (PyInit_nnstreamer_python), so IMO it is unnecessary.

**Comment by myungjoo** [comment]
> > and... do you think we need to rename it?
> > e.g., "libnnstreamer-python3.so"
> 
> I think this is related with python module name (PyInit_nnstreamer_python), so IMO it is unnecessary.

Ok!

**Review by myungjoo — APPROVED** [review]
LGTM

**Pull request merged**
