### PR TITLE
[Doc] Update meson build command options

### PR DESCRIPTION
**Pull request by uyw4687**
Update meson build command options

Signed-off-by: Seonkyo Ok uyw4687@naver.com

### CODE REVIEW

**Comment by dongju-chae** [comment]
Please add Signed-off-by line in your commit log message (`$ git commit -s ...`)

**Review by myungjoo — APPROVED** [review]
LGTM

**Comment by myungjoo** [comment]
You need to add Signed-off at the commit message, not PR message.
For DCO: https://github.com/nnstreamer/nnstreamer/pull/2937/checks?check_run_id=1528912994

The commit title is not appropriate.

**Comment by uyw4687** [comment]
updated commit message

**Review by jaeyun-jung — APPROVED** [review]

**Pull request merged**
