### PR TITLE
[TEST] remove meaningless test

### PR DESCRIPTION
**Pull request by yeonykim2**
- remove meaningless test
 - issue has been resolved

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped

### CODE REVIEW

**Review by songgot — APPROVED** [review]
LGTM

**Review by again4you — APPROVED** [review]
LGTM!

**Review by gichan-jang — APPROVED** [review]
LGTM!
Thank you for your first commit.

**Review by niley7464 — APPROVED** [review]
LGTM 👍

**Review by wooksong — APPROVED** [review]

**Pull request merged**
