### PR TITLE
[Release] commits to lts/1.6 branch

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Prepare next release, commits to lts/1.6 branch.
- support dynamic dimension in NNFW
- commits about android build options

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by myungjoo — APPROVED** [review]
This is cherry-picking pre-tested/merged commits to long-term-stable branch.

**Comment by jaeyun-jung** [comment]
Next release : Commits in this PR + https://github.com/nnstreamer/nnstreamer/pull/2893 + https://github.com/nnstreamer/nnstreamer/pull/2878

I will prepare next version after ONE team release new library.

**Review by anyj0527 — APPROVED** [review]
LGTM Thanks 👍

**Review by again4you — APPROVED** [review]
LGTM!

**Pull request merged**
