### PR TITLE
[Wait For #2901] [Query] Add the skeleton codes for 'Query' sub-plugin        

### PR DESCRIPTION
**Pull request by dongju-chae**
This patch adds the skeleton codes for `Query` sub-plugin.   
The `tensor_query` will be implemented as sub-plugin of `tensor_filter`.

Related issue: https://github.com/nnstreamer/nnstreamer/issues/2802
                                                             
Signed-off-by: Dongju Chae <dongju.chae@samsung.com>

### CODE REVIEW

**Comment by dongju-chae** [comment]
`tensor_query` interface was not decided.

**Comment by myungjoo** [comment]
This is rather tensor-fitler::query-flatbuf. The design requires a common class "query" that supports "query-flatbuf", "query-webhook", "query-protobuf", "query-...".

**Comment by dongju-chae** [comment]
> This is rather tensor-fitler::query-flatbuf. The design requires a common class "query" that supports "query-flatbuf", "query-webhook", "query-protobuf", "query-...".

That's right.

**Comment by dongju-chae** [comment]
According to incoming Edge-AI interface, it becomes too stale codes, thus let's close this.

**Pull request closed without merging**
