### PR TITLE
[Android] method to set surface

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Add new method to set a surface to video-sink element.
In Android application, developer can simply set SurfaceHolder object to glimagesink.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
https://github.com/nnstreamer/nnstreamer-example/pull/240
example to set surface to glimagesink

**Review by dongju-chae — APPROVED** [review]
LGTM

**Review by anyj0527 — APPROVED** [review]
LGTM👍👍 Thanks!

**Review by myungjoo — APPROVED** [review]
LGTM

**Pull request merged**
