### PR TITLE
JNI/NDK: Add llama2.c sources to nnstreamer.mk

### PR DESCRIPTION
**Pull request by wooksong**
This patch modifies nnstreamer.mk to import TensorFilter sub-plugin for llama2.c into NNStreamer's Android NDK build chain.

Signed-off-by: Wook Song <wook16.song@samsung.com>

### CODE REVIEW

**Review by myungjoo — APPROVED** [review]

**Review by myungjoo — CHANGES_REQUESTED** [review]
1. uh... where's tensor_filter_llama.c?
2. Can't this be a custom filter?

We have https://github.com/nnstreamer/nnstreamer/blob/2ef28f06953845dc2a8b85ece41c043febd25df9/tests/nnstreamer_example/custom_example_llama2/nnstreamer_customfilter_llama2.c

**Comment by wooksong** [comment]
> 1. uh... where's tensor_filter_llama.c?
> 2. Can't this be a custom filter?
> 
> We have https://github.com/nnstreamer/nnstreamer/blob/2ef28f06953845dc2a8b85ece41c043febd25df9/tests/nnstreamer_example/custom_example_llama2/nnstreamer_customfilter_llama2.c

1. https://github.com/niley7464/nnstreamer/blob/llama2c/ext/nnstreamer/tensor_filter/tensor_filter_llama2.cc
@niley7464 works on it.
2. We planned to make it as a custom filter (as you mentioned). But loading a .so file in Android requires another JNI or native implementation. Instead, it is better to go this way.

**Comment by niley7464** [comment]
> 1. uh... where's tensor_filter_llama.c?
> 2. Can't this be a custom filter?

1. I am working tensor_filter_llama2c.
https://github.com/nnstreamer/nnstreamer/pull/4583

**Review by myungjoo — APPROVED** [review]
LGTM.

**Review by jaeyun-jung — APPROVED** [review]

**Comment by jaeyun-jung** [comment]
can you do rebase to main latest?

**Comment by again4you** [comment]
Even though this PR is not passed the CI checks, it is necessary so I will merge it forcefully.

**Pull request merged**
