### PR TITLE
Fix PyTorch support for macOS @open sesame 11/17 17:21

### PR DESCRIPTION
**Pull request by higmo**
**Changes proposed in this PR:**
- Add alternative dependency to find libtorch through cmake during configuration
- Update the tutorial for building on macOS as tested on my ARM64 Monterey machine

I've made a fair amount of changes to the macOS tutorial to make it clearer and shorter, hopefully that'll be OK! 🙂

This follows our discussion on issue #3953 .

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped

### CODE REVIEW

**Review by myungjoo — APPROVED** [review]
LGTM.

To merge this, I need sign-off in each commit.


---
Add ```signed-off-by: NAME <EMAIL>``` at the commit message. (Linux kernel style. e.g., $ git commit --amend -s). This will address Github DCO, too. For the meaning of signed-off-by in nnstreamer, please refer to https://github.com/nnstreamer/nnstreamer/blob/main/Documentation/contributing.md#merge-criteria , which is to agree to https://github.com/nnstreamer/nnstreamer/blob/main/CODE_OF_CONDUCT.md

**Review by niley7464 — APPROVED** [review]
LGTM :)

**Review by songgot — APPROVED** [review]
LGTM

**Comment by higmo** [comment]
> @higmo As soon as you sign-off your commits, this will be merged.

@myungjoo Commits are now signed-off, sorry for the delay :)

**Comment by myungjoo** [comment]
The postbuild errors are not related with this change; let's ignore them.

**Pull request merged**
