### PR TITLE
[tensor_trainer] Remove flexible CAPS from src pad

### PR DESCRIPTION
**Pull request by songgot**
- Remove flexible CAPS from src pad because the output buffer is fixed to the values training_loss, training_accuracy, validation_loss and validation_accuracy

### CODE REVIEW

**Review by gichan-jang — APPROVED** [review]
LGTM

**Comment by gichan-jang** [comment]
If the only data to be pushed downstream is stats, I think it can be a sink type element without src pad.

**Review by niley7464 — APPROVED** [review]
LGTM!

**Comment by songgot** [comment]
> If the only data to be pushed downstream is stats, I think it can be a sink type element without src pad.

Thank you

**Pull request merged**
