### PR TITLE
[Fix/Filter] Fix tensors info initialization

### PR DESCRIPTION
**Pull request by kimjh12**
[Fix/Filter] Fix tensors info initialization

- Internal tensors-info is not correctly initialized for some sub filters, causing incompatible format error.

Signed-off-by: Junhwan Kim <jejudo.kim@samsung.com>

### CODE REVIEW

**Review by zhoonit — APPROVED** [review]
Nice Catch 👍

**Review by anyj0527 — COMMENTED** [review]
Thanks! How about call `gst_tensors_info_free`  in their cleanup func ?

**Comment by kimjh12** [comment]
> Thanks! How about call `gst_tensors_info_free` in their cleanup func ?

Alright. thx

**Review by anyj0527 — APPROVED** [review]
LGTM ✔

**Review by myungjoo — APPROVED** [review]

**Pull request merged**
