### PR TITLE
[Query] detach option on msg thread

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Add attr to create message thread, to release thread resource.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by gichan-jang** [comment]
Q. Currently, we are using `pthread_join` to release thread resources, why do we need this change?

**Comment by jaeyun-jung** [comment]
@gichan-jang 
In my local, it sometimes reports seg-fault while running unittests in gbs (w/ gst-launch-1.0).

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by dongju-chae — APPROVED** [review]
LGTM

**Pull request merged**
