### PR TITLE
[Edge/MQTT] Manifest for MQTT implementation @open sesame 3/4 11:03

### PR DESCRIPTION
**Pull request by myungjoo**
This describes more specific for #3104.
The assignees of #3104 should refer to this document for implementation.

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

**Comment by gichan-jang** [comment]
If mqtt is independent of nnstreamer, how about placing it at `gst/mqtt`?

**Comment by myungjoo** [comment]
> If mqtt is independent of nnstreamer, how about placing it at `gst/mqtt`?

That appears better! Thanks.

**Review by dongju-chae — APPROVED** [review]
LGTM

**Review by gichan-jang — APPROVED** [review]
LGTM

**Pull request merged**
