### PR TITLE
[Mux/Merge] change property name

### PR DESCRIPTION
**Pull request by jaeyun-jung**
change property name (sync mode and option), remove underbar in property name.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by gichan-jang — APPROVED** [review]
LGTM!
These changes synced with element properties of the tensor mux and merge.

**Comment by myungjoo** [comment]
Can you make it backward compatible?

CC: @jaeyun-jung @again4you Wouldn't this make problems in the outside and clients?

**Comment by jaeyun-jung** [comment]
Tizen TCT sync mode and option is not used.
odin only uses single-shot functions, so no problem.
Testcases and sample in nnstreamer-example / api repo need update for this change. (I found 3 files to be modified)

@helloahn plz check esar pipeline includes mux and merge elements.

**Comment by myungjoo** [comment]
There are nnstreamer pipeline users (both GST-API and ML-API) making prototypes. We do not have access to their applications.

**Comment by jaeyun-jung** [comment]
`sync-mode` and `sync_mode` both work well :)

**Review by again4you — APPROVED** [review]
LGTM!

**Pull request merged**
