### PR TITLE
Filter/TF2-Lite: remove unnecessary if in meson @open sesame 10/28 15:05

### PR DESCRIPTION
**Pull request by myungjoo**
TF2-Lite has all such data types enabled.
We do not need to check them.

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

**Comment by myungjoo** [comment]
Actually, tf2-lite packaging in Tizen has BUGS.
We need fixes in Tizen:
- https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/244525/
- https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow/+/244528/
- https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/244537/

But the fix for tf1-lite needs to wait for Tizen 6.5 start.

**Review by dongju-chae — APPROVED** [review]
LGTM

**Comment by myungjoo** [comment]
This needs to wait for https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/244537/ , which is waiting for Tizen 6.5 devel start.

**Review by helloahn — APPROVED** [review]
LGTM

**Pull request merged**
