### PR TITLE
[Android] Remove recently added testcases

### PR DESCRIPTION
**Pull request by anyj0527**
- Remove `-Wno-exceptions` flag from Android-snpe.mk
- Currently, the exception from tensor_filter is not handled properly in naive api
and causes test failure in specific build setting, so remove it
- This TCs could be restored after when this issue is fixed.

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Comment by gichan-jang** [comment]
How about using @ignore annotation?

**Comment by myungjoo** [comment]
@jaeyun-jung I think we have added ```-Wno-exceptions``` intentionally for some reasons related with ndk build. Is this ok now?

**Comment by jaeyun-jung** [comment]
@myungjoo `-fexceptions` to handle exceptions. `-Wno-exceptions` is now unnecessary. (preventing build error with snpe module)

**Review by jaeyun-jung — APPROVED** [review]
Later work let's handle exceptions from native code in java.

**Comment by anyj0527** [comment]
@myungjoo @jaeyun-jung The build flag `-Wno-exceptions` is not necessary for SNPE SDK v1.38+ (the very recent version is 1.41)
@gichan-jang The TCs that would be added may not be same as these. I think removing them is more neat.

**Review by myungjoo — APPROVED** [review]
Ok then. LGTM.

**Pull request merged**
