### PR TITLE
[Log] use internal log function

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Replace logutil - glib funcs, use predefined log functions.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by myungjoo — APPROVED** [review]
LGTM

**Review by anyj0527 — COMMENTED** [review]
Q. `ml_log*` and `nns_log*` are both used in many srcs. Are they should be unified?

**Comment by jaeyun-jung** [comment]
> Q. `ml_log*` and `nns_log*` are both used in many srcs. Are they should be unified?

discussion later: nnstreamer > nns_log* / api > ml_log* ?

**Review by anyj0527 — APPROVED** [review]

**Review by gichan-jang — APPROVED** [review]
LGTM

**Comment by anyj0527** [comment]
> > Q. ml_log* and nns_log* are both used in many srcs. Are they should be unified?
> 
> discussion later: nnstreamer > nns_log* / api > ml_log* ?

It seems good.

**Pull request merged**
