### PR TITLE
Increase warning level and resolve compiler warnings. @open sesame 7/30 10:39

### PR DESCRIPTION
**Pull request by myungjoo**
1. Increase warning level of meson from 1 --> 2.
2. Resolve all warnings.

TODO: Increase warning level further.

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

**Review by wooksong — APPROVED** [review]
Wow, what a great job!

**Comment by jaeyun-jung** [comment]
```
[142/202] Generating parsegrammar with a custom command.
../tools/development/parser/grammar.y:366.1-12: warning: deprecated directive: â€˜%pure-parserâ€™, use â€˜%define api.pureâ€™ [-Wdeprecated]
  366 | %pure-parser
      | ^~~~~~~~~~~~
      | %define api.pure
../tools/development/parser/grammar.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]

[162/202] Compiling C object 'tools/development/parser/3ebd7e6@@nnstreamer-parser@exe/meson-generated_.._grammar.tab.c.o'.
FAILED: tools/development/parser/3ebd7e6@@nnstreamer-parser@exe/meson-generated_.._grammar.tab.c.o 
ccache cc -Itools/development/parser/3ebd7e6@@nnstreamer-parser@exe -Itools/development/parser -I../tools/development/parser -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=gnu89 -g '-DVERSION="1.7.2"' '-DVERSION_MAJOR="1"' '-DVERSION_MINOR="7"' '-DVERSION_MICRO="2"' -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Waggregate-return -Wold-style-definition -Wdeclaration-after-statement '-DNNSTREAMER_CONF_FILE="/var/www/html/nnstreamer/TAOS-CI/ci/repo-workers/pr-checker/3425-202107301039110.29614305496216-702014be9396ba14d0db4e5cb1d2ec9997b27527/nnstreamer/nnstreamer.ini"' -DENABLE_TENSORFLOW=1 -DENABLE_TENSORFLOW_LITE=1 -DENABLE_PYTORCH=1 -DENABLE_CAFFE2=1 -DHAVE_ORC=1 -DENABLE_PROTOBUF=1 -MD -MQ 'tools/development/parser/3ebd7e6@@nnstreamer-parser@exe/meson-generated_.._grammar.tab.c.o' -MF 'tools/development/parser/3ebd7e6@@nnstreamer-parser@exe/meson-generated_.._grammar.tab.c.o.d' -o 'tools/development/parser/3ebd7e6@@nnstreamer-parser@exe/meson-generated_.._grammar.tab.c.o' -c tools/development/parser/grammar.tab.c
../tools/development/parser/grammar.y: In function â€˜gst_parse_free_referenceâ€™:
../tools/development/parser/grammar.y:222:30: error: cast between incompatible function types from â€˜void (*)(void *)â€™ to â€˜void (*)(void *, void *)â€™ [-Werror=cast-function-type]
  222 |   g_slist_foreach (rr->pads, (GFunc) g_free, NULL);
      |                              ^
../tools/development/parser/grammar.y: In function â€˜priv_gst_parse_yyparseâ€™:
../tools/development/parser/grammar.y:450:48: error: cast between incompatible function types from â€˜void (*)(void *)â€™ to â€˜void (*)(void *, void *)â€™ [-Werror=cast-function-type]
  450 |        g_slist_foreach ($$->last.pads, (GFunc) g_free, NULL);
      |                                                ^
../tools/development/parser/grammar.y:646:42: error: cast between incompatible function types from â€˜void (*)(void *)â€™ to â€˜void (*)(void *, void *)â€™ [-Werror=cast-function-type]
  646 |         g_slist_foreach ($2, (GFunc) g_free, NULL);
      |                                          ^
../tools/development/parser/grammar.y: In function â€˜priv_gst_parse_launchâ€™:
../tools/development/parser/grammar.y:828:29: error: cast between incompatible function types from â€˜void (*)(link_t *)â€™ {aka â€˜void (*)(struct <anonymous> *)â€™} to â€˜void (*)(void *, void *)â€™ [-Werror=cast-function-type]
  828 |   g_slist_foreach (g.links, (GFunc)gst_parse_free_link, NULL);
      |                             ^
cc1: all warnings being treated as errors

```

**Comment by myungjoo** [comment]
The apptest is not working properly somehow.
When I build nnstreamer-example and run apptest with this PR, it runs ok in Ubuntu.

**Comment by myungjoo** [comment]
> The apptest is not working properly somehow.
> When I build nnstreamer-example and run apptest with this PR, it runs ok in Ubuntu.

It appears that CI server's local gcc is configured to be more strict.
The new PR includes warn-fixes for GFunc of parsers.

**Review by jaeyun-jung — APPROVED** [review]

**Pull request merged**
