### PR TITLE
test/query: revive pid retrieval

### PR DESCRIPTION
**Pull request by myungjoo**
In recent commits, pid assignment after invoking background processes
has disappeared. Revivde pid assignment so that we can kill unnecessary
processes and avoid indefinite waits.

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

### CODE REVIEW

**Review by anyj0527 — APPROVED** [review]
LGTM

**Comment by jaeyun-jung** [comment]
need rollback GC's PR (block hybrid testcases)?

**Comment by gichan-jang** [comment]
grpc/runTest.sh also uses `gstTestBackground`.

**Comment by myungjoo** [comment]
grpc test cases updated.

**Comment by myungjoo** [comment]
> need rollback GC's PR (block hybrid testcases)?

Don't need any rollbacks.

**Review by jaeyun-jung — APPROVED** [review]

**Pull request merged**
