### PR TITLE
[Edge] remove nns-edge @open sesame 07/20 10:34

### PR DESCRIPTION
**Pull request by jaeyun-jung**
nnstreamer-edge is moved to other repository.
Remove related files and build scrit.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by anyj0527 — APPROVED** [review]
LGTM✔

**Comment by myungjoo** [comment]
I guess it's time to merge this PR, right? (please rebase)

**Review by gichan-jang — APPROVED** [review]
LGTM

**Comment by myungjoo** [comment]
Ignoring unrelated TC fails.

**Pull request merged**
