### PR TITLE
[indent] Change indent style

### PR DESCRIPTION
**Pull request by gichan-jang**
Change coding style
  - no space after unary operators:
     `&  *  +  -  ~  !  sizeof  typeof  alignof  __attribute__  defined`
reference: https://www.kernel.org/doc/html/v4.10/process/coding-style.html

Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>

Self evaluation:
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by jaeyun-jung — APPROVED** [review]

**Review by anyj0527 — APPROVED** [review]
LGTM ✔

**Comment by wooksong** [comment]
Q. GStreamer has its own policy. Is this PR compatible with that policy?

**Comment by gichan-jang** [comment]
> Q. GStreamer has its own policy. Is this PR compatible with that policy?

Yes, you can check it with `gst-indent` tool.
Previously, we used the same indent rule, but CI couldn't detect it.
(https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/developing.html#what-is-the-coding-style-for-gstreamer-code)

**Comment by wooksong** [comment]
> > Q. GStreamer has its own policy. Is this PR compatible with that policy?
> 
> Yes, you can check it with `gst-indent` tool.
> Previously, we used the same indent rule, but CI couldn't detect it.
> (https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/developing.html#what-is-the-coding-style-for-gstreamer-code)

Got it. Thanks.

**Comment by wooksong** [comment]
> > Q. GStreamer has its own policy. Is this PR compatible with that policy?
> 
> Yes, you can check it with `gst-indent` tool.
> Previously, we used the same indent rule, but CI couldn't detect it.
> (https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/developing.html#what-is-the-coding-style-for-gstreamer-code)

```bash
$ indent \
>   --braces-on-if-line \
>   --case-brace-indentation0 \
>   --case-indentation2 \
>   --braces-after-struct-decl-line \
>   --line-length80 \
>   --no-tabs \
>   --cuddle-else \
>   --dont-line-up-parentheses \
>   --continuation-indentation4 \
>   --honour-newlines \
>   --tab-size8 \
>   --indent-level2 ./ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
$ git diff
$ 
```

I've tested using tensordec-directvideo.c, but there is no indent issue in it. Have I missed something?

**Comment by gichan-jang** [comment]
@wooksong What's the version of the indent?
```
gichan@gichan:~/workspace/nnstreamer$ indent --version
GNU indent 2.2.12
```

My result is:
```
gichan@gichan:~/workspace/nnstreamer$ indent \
>   --braces-on-if-line \
>   --case-brace-indentation0 \
>   --case-indentation2 \
>   --braces-after-struct-decl-line \
>   --line-length80 \
>   --no-tabs \
>   --cuddle-else \
>   --dont-line-up-parentheses \
>   --continuation-indentation4 \
>   --honour-newlines \
>   --tab-size8 \
>   --indent-level2 \
>   ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
gichan@gichan:~/workspace/nnstreamer$ git diff
diff --git a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
index 06a019ce..1e400a90 100644
--- a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
+++ b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
@@ -34,8 +34,8 @@
 #include <nnstreamer_log.h>
 #include "tensordecutil.h"
 
-void init_dv (void) __attribute__ ((constructor));
-void fini_dv (void) __attribute__ ((destructor));
+void init_dv (void) __attribute__((constructor));
+void fini_dv (void) __attribute__((destructor));
```

and
```
gichan@gichan:~/workspace/nnstreamer$ ./tools/development/gst-indent ext/nnstreamer/tensor_decoder/tensordec-directvideo.c 
gichan@gichan:~/workspace/nnstreamer$ git diff
diff --git a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
index 06a019ce..1e400a90 100644
--- a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
+++ b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
@@ -34,8 +34,8 @@
 #include <nnstreamer_log.h>
 #include "tensordecutil.h"
 
-void init_dv (void) __attribute__ ((constructor));
-void fini_dv (void) __attribute__ ((destructor));
+void init_dv (void) __attribute__((constructor));
+void fini_dv (void) __attribute__((destructor));
```

**Comment by wooksong** [comment]
> @wooksong What's the version of the indent?
> 
> ```
> gichan@gichan:~/workspace/nnstreamer$ indent --version
> GNU indent 2.2.12
> ```
> 
> My result is:
> 
> ```
> gichan@gichan:~/workspace/nnstreamer$ indent \
> >   --braces-on-if-line \
> >   --case-brace-indentation0 \
> >   --case-indentation2 \
> >   --braces-after-struct-decl-line \
> >   --line-length80 \
> >   --no-tabs \
> >   --cuddle-else \
> >   --dont-line-up-parentheses \
> >   --continuation-indentation4 \
> >   --honour-newlines \
> >   --tab-size8 \
> >   --indent-level2 \
> >   ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> gichan@gichan:~/workspace/nnstreamer$ git diff
> diff --git a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> index 06a019ce..1e400a90 100644
> --- a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> +++ b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> @@ -34,8 +34,8 @@
>  #include <nnstreamer_log.h>
>  #include "tensordecutil.h"
>  
> -void init_dv (void) __attribute__ ((constructor));
> -void fini_dv (void) __attribute__ ((destructor));
> +void init_dv (void) __attribute__((constructor));
> +void fini_dv (void) __attribute__((destructor));
> ```
> 
> and
> 
> ```
> gichan@gichan:~/workspace/nnstreamer$ ./tools/development/gst-indent ext/nnstreamer/tensor_decoder/tensordec-directvideo.c 
> gichan@gichan:~/workspace/nnstreamer$ git diff
> diff --git a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> index 06a019ce..1e400a90 100644
> --- a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> +++ b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> @@ -34,8 +34,8 @@
>  #include <nnstreamer_log.h>
>  #include "tensordecutil.h"
>  
> -void init_dv (void) __attribute__ ((constructor));
> -void fini_dv (void) __attribute__ ((destructor));
> +void init_dv (void) __attribute__((constructor));
> +void fini_dv (void) __attribute__((destructor));
> ```

```bash
$ indent --version
GNU indent 2.2.11
```

Is this related to the version of ```indent```?

**Comment by wooksong** [comment]
> > @wooksong What's the version of the indent?
> > ```
> > gichan@gichan:~/workspace/nnstreamer$ indent --version
> > GNU indent 2.2.12
> > ```
> > 
> > 
> > My result is:
> > ```
> > gichan@gichan:~/workspace/nnstreamer$ indent \
> > >   --braces-on-if-line \
> > >   --case-brace-indentation0 \
> > >   --case-indentation2 \
> > >   --braces-after-struct-decl-line \
> > >   --line-length80 \
> > >   --no-tabs \
> > >   --cuddle-else \
> > >   --dont-line-up-parentheses \
> > >   --continuation-indentation4 \
> > >   --honour-newlines \
> > >   --tab-size8 \
> > >   --indent-level2 \
> > >   ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > gichan@gichan:~/workspace/nnstreamer$ git diff
> > diff --git a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > index 06a019ce..1e400a90 100644
> > --- a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > +++ b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > @@ -34,8 +34,8 @@
> >  #include <nnstreamer_log.h>
> >  #include "tensordecutil.h"
> >  
> > -void init_dv (void) __attribute__ ((constructor));
> > -void fini_dv (void) __attribute__ ((destructor));
> > +void init_dv (void) __attribute__((constructor));
> > +void fini_dv (void) __attribute__((destructor));
> > ```
> > 
> > 
> > and
> > ```
> > gichan@gichan:~/workspace/nnstreamer$ ./tools/development/gst-indent ext/nnstreamer/tensor_decoder/tensordec-directvideo.c 
> > gichan@gichan:~/workspace/nnstreamer$ git diff
> > diff --git a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > index 06a019ce..1e400a90 100644
> > --- a/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > +++ b/ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
> > @@ -34,8 +34,8 @@
> >  #include <nnstreamer_log.h>
> >  #include "tensordecutil.h"
> >  
> > -void init_dv (void) __attribute__ ((constructor));
> > -void fini_dv (void) __attribute__ ((destructor));
> > +void init_dv (void) __attribute__((constructor));
> > +void fini_dv (void) __attribute__((destructor));
> > ```
> 
> ```shell
> $ indent --version
> GNU indent 2.2.11
> ```
> 
> Is this related to the version of `indent`?

FYI, I found the reason from the changelog of indent.

2018-09-02 Andrej Shadura <andrew@shadura.me>                                   
 * Add C99 and C11 keywords; add typeof.                                     
 * Don’t insert a space between ! in !!x                                     
 * Don’t insert a space after __attribute__ when -bs is disabled             
 * Include -nbs in -linux

**Review by wooksong — CHANGES_REQUESTED** [review]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commits/master?utf8=%E2%9C%93&search=Add+--leave-preprocessor-space+for+indent+2.2.11

IMHO, we do not need this PR. For GNU indent 2.2.12, the option, ```--leave-preprocessor-space``` should be given.

**Comment by myungjoo** [comment]
Is it compatible with /tools/development/gst-indent ? If so, it's good to be merged.

**Review by wooksong — APPROVED** [review]
After offline discussion, we decide to use indent 2.2.12.

**Pull request merged**
