### PR TITLE
[Tools/Confchk] Show custom property description for sub-plugins @open sesame 10/15 19:48

### LINKED ISSUE #2782: [Feature] Custom property description of filter/decoder/conv subplugins for users (at runtime or doc)
We need a mechanism to show custom property descriptions of each sub-plugin for users.

- [x] Add a common interface for sub-plugins to register the description text
- [x] Add a mechanism to show sub-plugin info with "nnstreamer-check" utility (/tools/development/confchk)
- [x] Package/publish/release the utility, "nnstreamer-check" for uesrs.

### PR DESCRIPTION
**Pull request by dongju-chae**
This patch adds feature to show custom property description for
registered sub-plugins.

Related issue: #2782

Please share your opinions on better text formatting or recommended structure that contains related info.

For example, we can expect the following result
```
$ ./nnstreamer-check
...
NNStreamer registered sub-plugins:                                                           
============================================================                                 
                                                                                             
[Filter]                                                                                     
  cpp                                                                                        
    - No custom property found                                                               
  openvino                                                                                   
    - No custom property found                                                               
  tensorflow-lite                                                                            
    - Prop1: Descriptions1                                                                   
    - Prop2: Descriptions2                                                                   
  snpe                                                                                       
    - No custom property found                                                               
  caffe2                                                                                     
    - No custom property found                                                               
  python3                                                                                    
    - No custom property found                                                               
  python2                                                                                    
    - No custom property found                                                               
  edgetpu                                                                                    
    - No custom property found                                                               
  pytorch                                                                                    
    - No custom property found                                                               
  tensorflow                                                                                 
    - No custom property found                                                               
                                                                                             
[Decoder]                                                                                    
  image_segment                                                                              
    - No custom property found                                                               
  direct_video                                                                               
    - No custom property found                                                               
  flatbuf                                                                                    
    - No custom property found                                                               
  bounding_boxes                                                                             
    - No custom property found                                                               
  protobuf                                                                                   
    - Prop1: Descriptions1                                                                   
    - Prop2: Descriptions2                                                                   
  image_labeling                                                                             
    - No custom property found                                                               
  pose_estimation                                                                            
    - No custom property found                                                               
                                                                                             
[Conterver]                                                                                  
  libnnstreamer_converter_protobuf                                                           
    - No custom property found                                                               
  libnnstreamer_converter_flatbuf                                                            
    - Prop1: Descriptions1                                                                   
    - Prop2: Descriptions2                                                                   
```

if we add descriptions for custom properties like below
```
diff --git a/ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc b/ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
index 0a216f1..7f95711 100644
--- a/ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
+++ b/ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
@@ -163,6 +163,10 @@ void
 init_fbc (void)
 {
   registerExternalConverter (&flatBuf);
+  nnstreamer_converter_set_custom_property_desc (converter_subplugin_flatbuf,
+      "Prop1", "Descriptions1",
+      "Prop2", "Descriptions2",
+      NULL);
 }
 
 /** @brief Destruct this object for tensor converter sub-plugin */
diff --git a/ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc b/ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
index af3f726..a3fcc34 100644
--- a/ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
+++ b/ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
@@ -95,6 +95,11 @@ void
 init_pb (void)
 {
   nnstreamer_decoder_probe (&protobuf);
+  nnstreamer_decoder_set_custom_property_desc (decoder_subplugin_protobuf,
+      "Prop1", "Descriptions1",
+      "Prop2", "Descriptions2",
+      NULL);
+
 }
 
 /** @brief Destruct this object for tensordec-plugin */
diff --git a/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc b/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
index 0dac5f5..c40cc70 100644
--- a/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
+++ b/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
@@ -1180,6 +1180,10 @@ void
 init_filter_tflite (void)
 {
   nnstreamer_filter_probe (&NNS_support_tensorflow_lite);
+  nnstreamer_filter_set_custom_property_desc (filter_subplugin_tensorflow_lite,
+      "Prop1", "Descriptions1",
+      "Prop2", "Descriptions2",
+      NULL);
 }
 
 /** @brief Destruct the subplugin */
```

Signed-off-by: Dongju Chae <dongju.chae@samsung.com>

### CODE REVIEW

**Comment by dongju-chae** [comment]
The CI task for `cppcheck` looks strange...?

**Comment by myungjoo** [comment]
Wouldn't it be more intuitive if you simply add a list of "name" and "description" pairs to the Framework struct (e.g., GstTensorFilterFramework data structure)

**Comment by dongju-chae** [comment]
> Wouldn't it be more intuitive if you simply add a list of "name" and "description" pairs to the Framework struct (e.g., add an optional property at the end of the GstTensorFilterFramework data structure)

I have also considered your suggestion, but this feature should be a common interface for sub-plugins (e.g., filter, decoder, and converter). So, that's why I utilized a more abstract structure (i.e., `nnstreamer_subplugin`.

**Comment by myungjoo** [comment]
Ok, then, please rename the function.
E.g.,
```nnstreamer_filter_set_custom_property ```
==>
```nnstreamer_filter_set_custom_property_description ```

**Review by myungjoo — APPROVED** [review]
LGTM. (Rename API names)

**Comment by dongju-chae** [comment]
> Ok, then, please rename the function.

Got it. thanks.

**Review by anyj0527 — APPROVED** [review]
LGTM Thanks! Near future We should update the custom_property_desc of each module!

**Pull request merged**
