### PR TITLE
[Filter] unnecessary initialization

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Remove unnecessary init while parsing accel string.
- fetch fw info to parse accel for the case if nn framework is not opened.
- check fw info if open() callback of nn framework is not written.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by myungjoo** [comment]
Is this ok with the usage in ```_gtfc_setprop_ACCELERATOR ( ) ```?


If it's not ok, for the optimization you've mentioned, we may add a init-check member in GstTensorFilterFrameworkInit.

**Review by songgot — APPROVED** [review]
Looks good to me.

**Comment by jaeyun-jung** [comment]
To reviewers, 2022-04-14 PR updated
- consider fetching framework info if nnfw is not opened.

**Comment by myungjoo** [comment]
> To reviewers, 2022-04-14 PR updated. Please review the changes again.
> 
> * consider fetching framework info if nnfw is not opened.

PTAL: @songgot @anyj0527

**Comment by anyj0527** [comment]
> > To reviewers, 2022-04-14 PR updated. Please review the changes again.
> > 
> > * consider fetching framework info if nnfw is not opened.
> 
> PTAL: @songgot @anyj0527

LGTM 👍

**Pull request merged**
