### PR TITLE
Update tutorial2_object_detection.md @open sesame 04/24 17:28

### PR DESCRIPTION
**Pull request by pasteldream-ps**
Add `nnstreamer-tensorflow2-lite` package to the install instruction in the tutorial

## Note
https://github.com/nnstreamer/nnstreamer/blob/main/.github/PULL_REQUEST_TEMPLATE.md which placed here has been removed by @wooksong

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
please add signed-off field on your commit (e.g. 'git commit -s --amend')

**Comment by gichan-jang** [comment]
@pasteldream-ps , Thanks for updating the tutorial.
The TAOS-CI checks the singed-off. Please add sign and update PR.
```
$ git commit -s --amend --no-edit
$ git push --force # You need force push to update current PR.
```

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by myungjoo — APPROVED** [review]

**Comment by myungjoo** [comment]
@pasteldream-ps You need to sign your commit off, which means that you are good with the contributing agreements (e.g., licenses, patents, copyrights, and so on)

**Review by anyj0527 — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
