### PR TITLE
[Filter/TF-lite] tensor name in meta

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Set tensor name in tensors info struct.

TODO: we should update testcases in api repo later.
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
Request from Tizen MM team.

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by again4you — APPROVED** [review]
LGTM!

**Comment by again4you** [comment]
The operation is verified by Taeyoung Chung, who requests this functionality. However, the below test case is not merged yet.
* https://review.tizen.org/gerrit/#/c/test/tct/native/api/+/254698/

**Pull request merged**
