### PR TITLE
[test/tf2lite] Add tests for tf2lite2 sub-plugin

### PR DESCRIPTION
**Pull request by anyj0527**
- Add gtest based unittests for tensorflow2-lite sub-plugin
  They test the result of mobilenet models when the orange image is given
- Add a float type tflite model "mobilenet_v2_1.0_224.tflite"

- Add filter extension test for tf2lite sub-plugin 

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by myungjoo — COMMENTED** [review]
We already have ```mobilenet_v2_1.0_224_quant.tflite``` in /tests/test_models. Can you reuse this model file to save some space?

**Comment by anyj0527** [comment]
@myungjoo To examine the functionality of XNNPACK delegate, float-typed models are needed. To save the space, I'll replace the newly added model with smaller one.

**Comment by myungjoo** [comment]
> @myungjoo To examine the functionality of XNNPACK delegate, float-typed models are needed. To save the space, I'll replace the newly added model with smaller one.

Ah.. ok. I've got it.

**Review by myungjoo — APPROVED** [review]
LGTM

**Review by jaeyun-jung — APPROVED** [review]

**Pull request merged**
