### PR TITLE
[API/Tizen] Add verson number to libcapi-nnstreamer.so

### PR DESCRIPTION
**Pull request by again4you**
This patch adds the verson number to libcapi-nnstreamer.so and fixes the
packaging issue as follows:

```bash
$ rpm -qlp capi-nnstreamer-1.5.3-0.x86_64.rpm
/usr/lib64/libcapi-nnstreamer.so.0
/usr/lib64/libcapi-nnstreamer.so.1
/usr/lib64/libcapi-nnstreamer.so.1.5.3
/usr/share/licenses/capi-nnstreamer
/usr/share/licenses/capi-nnstreamer/LICENSE

$ rpm -qlp capi-nnstreamer-devel-1.5.3-0.x86_64.rpm
/usr/include/nnstreamer/nnstreamer-single.h
/usr/include/nnstreamer/nnstreamer.h
/usr/lib64/libcapi-nnstreamer.so
/usr/lib64/pkgconfig/capi-nnstreamer.pc
```

Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed []Skipped
2. Run test: [*]Passed [ ]Failed []Skipped

#### Submit v2
* Add libcapi-nnstreamer.so.0 symlink to temporarily support the backward compatibility of the .Net APIs  and rootstrap

#### Submit v1
* First draft

### Notice 
~~DO NOT apply this patch only into review.tizen.org.~~

~~If this patch is merged, all .net test cases would be failed since it refers to `libcapi-nnstreamer.so.0` instead of `libcapi-nnstreamer.so.1`. So TizenFx should be fixed and merged it with the same SR tag.~~

### CODE REVIEW

**Comment by myungjoo** [comment]
> Notice
DO NOT apply this patch only into review.tizen.org.
>
> If this patch is merged, all .net test cases would be failed since it refers to libcapi-nnstreamer.so.0 instead of libcapi-nnstreamer.so.1. So TizenFx should be fixed and merged it with the same SR tag.

Can we add libcapi-nnstreamer.so.0 symlink as a intermediate fix?

==>
1. add both.so.0 & .so.1 to nnstreamer packaging
2. modify TizenFX
3. remove .so.0 from nnstreamer packaging

**Comment by again4you** [comment]
> > Notice
> > DO NOT apply this patch only into review.tizen.org.
> > If this patch is merged, all .net test cases would be failed since it refers to libcapi-nnstreamer.so.0 instead of libcapi-nnstreamer.so.1. So TizenFx should be fixed and merged it with the same SR tag.
> 
> Can we add libcapi-nnstreamer.so.0 symlink as a intermediate fix?
> 
> ==>
> 
>     1. Week 0: add both.so.0 & .so.1 to nnstreamer packaging / do SR
> 
>     2. Week 1: modify TizenFX / do SR
> 
>     3. Week 2: remove .so.0 from nnstreamer packaging / do SR

Possibie solutions.
1. @myungjoo 's approach

2. Fix the TizenFx and merge it with the same SR tag.

Both of them are good to me.

**Comment by again4you** [comment]
@gichan-jang  tested this patch on TM1 device and all unit test of C# APIs is passed without any errors.

**Review by myungjoo — APPROVED** [review]
LGTM. but wait for TizenFX handling (I believe @again4you will handle all related matters :)  )

**Review by myungjoo — CHANGES_REQUESTED** [review]
It'd be better to let meson create .so.{versionname} files automatically.

**Review by myungjoo — APPROVED** [review]

**Comment by again4you** [comment]
> It'd be better to let meson create .so.{versionname} files automatically.

The second patch just makes an "*.so.0" symlink as a workaround for TizenFX.
Because of this reason, all test cases are passed without modifying TizenFX code.

After releasing Tizen M2, I will fix TizenFX and remove this workaround symlink.

**Review by wooksong — APPROVED** [review]
Looks good to me!

**Pull request merged**
