### PR TITLE
[Edge] Change input parameter type of the nns_edge_data_get.

### PR DESCRIPTION
**Pull request by gichan-jang**
Change input parameter type of the nns_edge_data_get. 

* Need to force merge and group SR with https://github.com/nnstreamer/nnstreamer-edge/pull/107.

Signed-off-by: gichan <gichan2.jang@samsung.com>

**Self evaluation:**
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Comment by myungjoo** [comment]
Forgot to include a header file?

**Comment by jaeyun-jung** [comment]
> Forgot to include a header file?

need SR to fix build error.

**Review by jaeyun-jung — APPROVED** [review]

**Review by again4you — APPROVED** [review]
LGTM!

**Review by jihochu — APPROVED** [review]
LGTM

**Pull request merged**
